id: IECCF44B6
legacy_id: P010476
ocr_import_info:
  bdrc_scan_id: W7445
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:36:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:14:58.513176+00:00'
last_modified: 2022-09-04 11:15:05.480900
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W7445
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW7445
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གུང་ཐང་བྱུང་རབས་དཀར་ཆག
  author: འཇོག་རི་ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས།
statistics:
  ocr_word_mean_confidence_index: 0.4988242632650716
  ocr_word_median_confidence_index: 0.4300000071525574
quality: null
bases:
  I1KG22897:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22897
      total_pages: 156
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22897.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.4988242632650716
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
