id: IECCF44B6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:37:42+00:00'
last_modified: '2022-06-08T13:53:06.035623+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W7445
  title: གུང་ཐང་བྱུང་རབས་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0EB4:
      image_group_id: I1KG22897
      title: ''
      total_pages: 156
      order: 1
      base_file: 0EB4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
