id: P010476
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W7445
  title: གུང་ཐང་བྱུང་རབས་དཀར་ཆག
  author: ''
  volumes:
    23c6e90d0804419ba47509ce15c44ad2:
      image_group_id: I1KG22897
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
