id: P010476
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:51:49.235732
source_metadata:
  id: bdr:W7445
  title: གུང་ཐང་བྱུང་རབས་དཀར་ཆག
  author: ''
  volumes:
    23c6e90d0804419ba47509ce15c44ad2:
      image_group_id: I1KG22897
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
